### ISSUE TITLE
How to run the server?

### ISSUE THREAD

**Issue by Tam66662** [hummatli/cAndroid#1]
Hi, sorry if this is an easy answer.  I'm new to Android development and Android Studio.  I downloaded your project, and I can compile both the server and client modules.  But I am only able to run the Client on my Android device.  How do I run the server on the PC?  There is no option to do this in Android Studio.

![image](https://user-images.githubusercontent.com/12551526/32581985-4aff7834-c4a1-11e7-985d-914726955273.png)

**Comment by hummatli** [comment]
Hi, @Tam66662. That is simple java file. 
Find [Start.java](https://github.com/hummatli/cAndroid/blob/master/cAndroid/cAndroidServer/src/main/java/com/mobapphome/candroid/server/Start.java) file. Click right button of the mouse. Find run in the context menu and click it. It will run and will listen on the port (6000).  You can change it in the main function.


Don't forget to star the project if you liked it. :)

**Comment by Tam66662** [comment]
Ahh, there it is!  Great!  And it works too.  Thanks!

**Comment by hummatli** [comment]
Fine 👍 . Not at all.
